name: Build and Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "latest"
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
        env:
          REACT_APP_STARSWAP_BOOST: ${{ secrets.BOOST }}
          REACT_APP_INFURA_KEY: ${{ secrets.INFURA_KEY }}
          CI: false

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
